export const CURRENCIES = {
  SYP: 'SYP',
  USD: 'USD'
};

export const SUPPORTED_CURRENCIES = Object.values(CURRENCIES);

export const PRODUCT_UNITS = [
  { value: 'قطعة', label: 'قطعة' },
  { value: 'كيلوغرام', label: 'كيلوغرام' },
  { value: 'غرام', label: 'غرام' },
  { value: 'لتر', label: 'لتر' },
  { value: 'متر', label: 'متر' },
  { value: 'صندوق', label: 'صندوق' },
  { value: 'عبوة', label: 'عبوة' },
  { value: 'حبة', label: 'حبة' }
];

export const PRICE_TIER_CODES = [
  { value: 'RETAIL', label: 'مفرق' },
  { value: 'WHOLESALE', label: 'جملة' },
  { value: 'SPECIAL', label: 'سعر خاص' }
];

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  CASHIER: 'CASHIER',
  ACCOUNTANT: 'ACCOUNTANT',
  SALES: 'SALES',
  PURCHASES: 'PURCHASES',
  INVENTORY: 'INVENTORY',
  REPORTS: 'REPORTS'
};

export const ALL_USER_ROLES = Object.values(USER_ROLES);

export const PERMISSIONS = {
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_CREATE: 'inventory.create',
  INVENTORY_EDIT: 'inventory.edit',
  INVENTORY_DELETE: 'inventory.delete',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',
  CUSTOMERS_COLLECT: 'customers.collect',
  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_EDIT: 'suppliers.edit',
  SUPPLIERS_SETTLE: 'suppliers.settle',
  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_EDIT: 'sales.edit',
  SALES_CANCEL: 'sales.cancel',
  SALES_APPROVE: 'sales.approve',
  SALES_OVERRIDE_LOCK: 'sales.override-lock',
  SALES_PRINT: 'sales.print',
  SALES_EXPORT: 'sales.export',
  PURCHASES_VIEW: 'purchases.view',
  PURCHASES_CREATE: 'purchases.create',
  PURCHASES_EDIT: 'purchases.edit',
  PURCHASES_CANCEL: 'purchases.cancel',
  PURCHASES_APPROVE: 'purchases.approve',
  PURCHASES_OVERRIDE_LOCK: 'purchases.override-lock',
  PURCHASES_PRINT: 'purchases.print',
  PURCHASES_EXPORT: 'purchases.export',
  EXPENSES_VIEW: 'expenses.view',
  EXPENSES_CREATE: 'expenses.create',
  EXPENSES_EDIT: 'expenses.edit',
  EXPENSES_DELETE: 'expenses.delete',
  EXPENSES_APPROVE: 'expenses.approve',
  EXPENSES_OVERRIDE_LOCK: 'expenses.override-lock',
  EXPENSES_EXPORT: 'expenses.export',
  REPORTS_VIEW: 'reports.view',
  REPORTS_PRINT: 'reports.print',
  REPORTS_EXPORT: 'reports.export',
  EXCHANGE_RATE_VIEW: 'exchange-rate.view',
  EXCHANGE_RATE_MANAGE: 'exchange-rate.manage',
  CURRENCY_EXCHANGE_VIEW: 'currency-exchange.view',
  CURRENCY_EXCHANGE_CREATE: 'currency-exchange.create',
  CURRENCY_EXCHANGE_EXPORT: 'currency-exchange.export',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',
  SETTINGS_YEAR_END: 'settings.year-end',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_RESET_PASSWORD: 'users.reset-password'
};

export const PERMISSION_DEFINITIONS = [
  { key: PERMISSIONS.INVENTORY_VIEW, module: 'inventory', action: 'view', label: 'عرض المخزون والمنتجات' },
  { key: PERMISSIONS.INVENTORY_CREATE, module: 'inventory', action: 'create', label: 'إنشاء منتجات/تصنيفات' },
  { key: PERMISSIONS.INVENTORY_EDIT, module: 'inventory', action: 'edit', label: 'تعديل المنتجات/التصنيفات' },
  { key: PERMISSIONS.INVENTORY_DELETE, module: 'inventory', action: 'delete', label: 'تعطيل/حذف سجلات المخزون' },
  { key: PERMISSIONS.CUSTOMERS_VIEW, module: 'customers', action: 'view', label: 'عرض العملاء' },
  { key: PERMISSIONS.CUSTOMERS_CREATE, module: 'customers', action: 'create', label: 'إنشاء عميل' },
  { key: PERMISSIONS.CUSTOMERS_EDIT, module: 'customers', action: 'edit', label: 'تعديل العملاء' },
  { key: PERMISSIONS.CUSTOMERS_COLLECT, module: 'customers', action: 'collect', label: 'تحصيل ذمم العملاء' },
  { key: PERMISSIONS.SUPPLIERS_VIEW, module: 'suppliers', action: 'view', label: 'عرض الموردين' },
  { key: PERMISSIONS.SUPPLIERS_CREATE, module: 'suppliers', action: 'create', label: 'إنشاء مورد' },
  { key: PERMISSIONS.SUPPLIERS_EDIT, module: 'suppliers', action: 'edit', label: 'تعديل الموردين' },
  { key: PERMISSIONS.SUPPLIERS_SETTLE, module: 'suppliers', action: 'settle', label: 'سداد ذمم الموردين' },
  { key: PERMISSIONS.SALES_VIEW, module: 'sales', action: 'view', label: 'عرض فواتير المبيعات' },
  { key: PERMISSIONS.SALES_CREATE, module: 'sales', action: 'create', label: 'إنشاء فواتير المبيعات' },
  { key: PERMISSIONS.SALES_EDIT, module: 'sales', action: 'edit', label: 'تعديل المبيعات' },
  { key: PERMISSIONS.SALES_CANCEL, module: 'sales', action: 'cancel', label: 'إلغاء فواتير المبيعات' },
  { key: PERMISSIONS.SALES_APPROVE, module: 'sales', action: 'approve', label: 'اعتماد فواتير المبيعات' },
  { key: PERMISSIONS.SALES_OVERRIDE_LOCK, module: 'sales', action: 'override-lock', label: 'تجاوز قفل المبيعات المعتمدة' },
  { key: PERMISSIONS.SALES_PRINT, module: 'sales', action: 'print', label: 'طباعة المبيعات' },
  { key: PERMISSIONS.SALES_EXPORT, module: 'sales', action: 'export', label: 'تصدير المبيعات' },
  { key: PERMISSIONS.PURCHASES_VIEW, module: 'purchases', action: 'view', label: 'عرض فواتير المشتريات' },
  { key: PERMISSIONS.PURCHASES_CREATE, module: 'purchases', action: 'create', label: 'إنشاء فواتير المشتريات' },
  { key: PERMISSIONS.PURCHASES_EDIT, module: 'purchases', action: 'edit', label: 'تعديل المشتريات' },
  { key: PERMISSIONS.PURCHASES_CANCEL, module: 'purchases', action: 'cancel', label: 'إلغاء فواتير المشتريات' },
  { key: PERMISSIONS.PURCHASES_APPROVE, module: 'purchases', action: 'approve', label: 'اعتماد فواتير المشتريات' },
  { key: PERMISSIONS.PURCHASES_OVERRIDE_LOCK, module: 'purchases', action: 'override-lock', label: 'تجاوز قفل المشتريات المعتمدة' },
  { key: PERMISSIONS.PURCHASES_PRINT, module: 'purchases', action: 'print', label: 'طباعة المشتريات' },
  { key: PERMISSIONS.PURCHASES_EXPORT, module: 'purchases', action: 'export', label: 'تصدير المشتريات' },
  { key: PERMISSIONS.EXPENSES_VIEW, module: 'expenses', action: 'view', label: 'عرض المصروفات' },
  { key: PERMISSIONS.EXPENSES_CREATE, module: 'expenses', action: 'create', label: 'إنشاء مصروف' },
  { key: PERMISSIONS.EXPENSES_EDIT, module: 'expenses', action: 'edit', label: 'تعديل المصروفات' },
  { key: PERMISSIONS.EXPENSES_DELETE, module: 'expenses', action: 'delete', label: 'إلغاء/حذف المصروفات' },
  { key: PERMISSIONS.EXPENSES_APPROVE, module: 'expenses', action: 'approve', label: 'اعتماد المصروفات' },
  { key: PERMISSIONS.EXPENSES_OVERRIDE_LOCK, module: 'expenses', action: 'override-lock', label: 'تجاوز قفل المصروفات المعتمدة' },
  { key: PERMISSIONS.EXPENSES_EXPORT, module: 'expenses', action: 'export', label: 'تصدير المصروفات' },
  { key: PERMISSIONS.REPORTS_VIEW, module: 'reports', action: 'view', label: 'عرض التقارير' },
  { key: PERMISSIONS.REPORTS_PRINT, module: 'reports', action: 'print', label: 'طباعة التقارير' },
  { key: PERMISSIONS.REPORTS_EXPORT, module: 'reports', action: 'export', label: 'تصدير التقارير' },
  { key: PERMISSIONS.EXCHANGE_RATE_VIEW, module: 'exchange-rate', action: 'view', label: 'عرض سعر الصرف' },
  { key: PERMISSIONS.EXCHANGE_RATE_MANAGE, module: 'exchange-rate', action: 'manage', label: 'إدارة سعر الصرف' },
  { key: PERMISSIONS.CURRENCY_EXCHANGE_VIEW, module: 'currency-exchange', action: 'view', label: 'عرض شراء/بيع الدولار' },
  { key: PERMISSIONS.CURRENCY_EXCHANGE_CREATE, module: 'currency-exchange', action: 'create', label: 'إنشاء عملية شراء/بيع دولار' },
  { key: PERMISSIONS.CURRENCY_EXCHANGE_EXPORT, module: 'currency-exchange', action: 'export', label: 'تصدير عمليات الدولار' },
  { key: PERMISSIONS.SETTINGS_VIEW, module: 'settings', action: 'view', label: 'عرض الإعدادات والإدارة' },
  { key: PERMISSIONS.SETTINGS_MANAGE, module: 'settings', action: 'manage', label: 'إدارة الإعدادات والنظام' },
  { key: PERMISSIONS.SETTINGS_YEAR_END, module: 'settings', action: 'year-end', label: 'أرشفة السنة المالية وإعادة الضبط' },
  { key: PERMISSIONS.USERS_VIEW, module: 'users', action: 'view', label: 'عرض المستخدمين' },
  { key: PERMISSIONS.USERS_CREATE, module: 'users', action: 'create', label: 'إنشاء مستخدم' },
  { key: PERMISSIONS.USERS_EDIT, module: 'users', action: 'edit', label: 'تعديل المستخدمين' },
  { key: PERMISSIONS.USERS_RESET_PASSWORD, module: 'users', action: 'reset-password', label: 'إعادة تعيين كلمات المرور' }
];
